# Generated by Django 6.1 on 2026-09-01 04:46

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('tax', 'Tax Filing'), ('sales_tax', 'Sales Tax'), ('company', 'Company Incorporation'), ('strn_ntn', 'STRN & NTN'), ('bookkeeping', 'Bookkeeping'), ('audit', 'Audit'), ('secp_fbr_kpra', 'SECP / FBR / KPRA'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=documents.models.upload_path)),
                ('note', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='The client this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
